### ISSUE TITLE
Some unit tests fail

### ISSUE THREAD

**Issue by vsht** [gituliar/fuchsia#14]
Tried to run the test-suite and encountered following issues:

```
make test-maxima
```
Output:
```bash
env SAGE_PATH="/media/Data/Projects/Other/forks/fuchsia" \
	sage -python -munittest -fv test.test_suite_maxima \
            2>&1 | tee test/test_suite_maxima.log
are_diagonal_blocks_reduced (fuchsia)
Doctest: fuchsia.are_diagonal_blocks_reduced ... ok, 0.726 sec
common_factor (fuchsia)
Doctest: fuchsia.common_factor ... ok, 0.012 sec
is_normalized (fuchsia)
Doctest: fuchsia.is_normalized ... ok, 0.030 sec
jordan_cell_sizes (fuchsia)
Doctest: fuchsia.jordan_cell_sizes ... ok, 0.001 sec
matrix_c0 (fuchsia)
Doctest: fuchsia.matrix_c0 ... ok, 0.017 sec
matrix_c1 (fuchsia)
Doctest: fuchsia.matrix_c1 ... ok, 0.187 sec
matrix_is_nilpotent (fuchsia)
Doctest: fuchsia.matrix_is_nilpotent ... ok, 0.007 sec
matrix_residue (fuchsia)
Doctest: fuchsia.matrix_residue ... ok, 0.007 sec
matrix_taylor0 (fuchsia)
Doctest: fuchsia.matrix_taylor0 ... ok, 0.006 sec
matrix_taylor1 (fuchsia)
Doctest: fuchsia.matrix_taylor1 ... ok, 0.009 sec
parse (fuchsia)
Doctest: fuchsia.parse ... ok, 0.004 sec
singularities (fuchsia)
Doctest: fuchsia.singularities ... ok, 0.035 sec
test_git_409 (test_normalize_by_blocks.Test) ... ERROR, 0.283 sec

======================================================================
ERROR: test_git_409 (test_normalize_by_blocks.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/Data/Projects/Other/forks/fuchsia/test/test_normalize_by_blocks.py", line 29, in test_git_409
    "data", "git_409.m"))
  File "/media/Data/Projects/Other/forks/fuchsia/test/test_normalize_by_blocks.py", line 16, in assertNormalizeBlocksWorks
    test.assertFalse(is_normalized(m, x, eps))
  File "fuchsia.py", line 920, in is_normalized
    M0 = matrix_residue(M, x, x0)
  File "fuchsia.py", line 447, in matrix_residue
    m0 = matrix_c0(M, x, x0, 0)
  File "fuchsia.py", line 404, in matrix_c0
    return matrix_taylor0(M, x, point, p+1)
  File "fuchsia.py", line 359, in matrix_taylor0
    return m.apply_map(lambda ex: limit_fixed(ex*(x-x0)**exp, x, x0))
  File "sage/matrix/matrix2.pyx", line 2054, in sage.matrix.matrix2.Matrix.apply_map (/builddir/build/BUILD/sage-7.6/src/build/cythonized/sage/matrix/matrix2.c:19105)
    values = [phi(v) for v in self.list()]
  File "fuchsia.py", line 359, in <lambda>
    return m.apply_map(lambda ex: limit_fixed(ex*(x-x0)**exp, x, x0))
  File "fuchsia.py", line 250, in limit_fixed
    return limit_fixed_maxima(expr, x, x0)
  File "fuchsia.py", line 268, in limit_fixed_maxima
    l = maxima_calculus.sr_limit(expr, x, x0)
  File "/usr/lib64/python2.7/site-packages/sage/interfaces/maxima_lib.py", line 973, in sr_limit
    self._missing_assumption(s)
  File "/usr/lib64/python2.7/site-packages/sage/interfaces/maxima_lib.py", line 1018, in _missing_assumption
    raise ValueError(outstr)
ValueError: Computation failed since Maxima requested additional constraints; using the 'assume' command before evaluation *may* help (example of legal syntax is 'assume(eps*(2*eps-1)*(3*eps-1)
>0)', see `assume?` for more details)
Is eps*(2*eps-1)*(3*eps-1)
    positive, negative or zero?

----------------------------------------------------------------------
Ran 13 tests in 1.324s

FAILED (errors=1)

```

Then

```
make test-maple
```

also fails because the input file `pap_3_50.m` (from `test/test_epsilon_form.py`) is missing.

My system is Fedora 26 64-bit,

```
Python 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux2
sagemath-7.6-3.fc26
maxima-5.40.0-4.fc26
```
Cheers,
Vladyslav

**Comment by gituliar** [comment]
As for `make test-maxima` everything works for me with Sage 7.0. Most likely, the problem you reported is because of using Sage 7.6. This is not a surprise since Sage is a very active project. We also faced differences when switching between Sage 6.x and Sage 7.0.

For the moment, we suggest all the users to use Sage 7.0, since this is a platform which we use for development. I think that we will update this suggestion with the next big release of Fuchsia.

PS. I am fixing the missing file.

**Comment by vsht** [comment]
I see. Unfortunately, on Fedora 26 I cannot easily downgrade to Sage 7.0. I guess I'll have to try a virtual machine. What particular Linux distro (that still ships Sage 7.0) do you recommend for Fuchsia?

**Comment by magv** [comment]
We don't recommend using distro-supplied Sage at all actually. We 
recommend using the installer from sagemath.org. This is because distros 
sometimes mix different versions of Sage core and dependent software 
(e.g. Maxima), and as you can see the whole thing is somewhat brittle, 
so it's best not to deviate from the upstream.

With that said, the downloads for Sage pre 7.5 have been removed from 
the mirrors, so recommending people use 7.0 is not really an option 
nowadays. We really should look into this error.

**Comment by vsht** [comment]
Understood. As you wrote, nowadays it does not seem possible to find the binaries of Sage 7.0 on
a public mirror. What is currently offered for Fedora from the official Sage website are the versions 8.0, 7.6 and 7.5.1. I guess all of them are "too new" for Fuchsia.

On the other hand, if I use Maple the error does not occur, so maybe I can get away with that for a while.

**Comment by vsht** [comment]
Would Rings (https://inspirehep.net/record/1641768) actually be a viable alternative to Maple and Sage in Fuchsia? The description looks quite promising.

**Comment by gituliar** [comment]
Looks like a promising project! At first sight it looks very close to GiNaC (remember, however, that GiNaC is a mature project with some additional features) and both could be used to implement Fuchsia. For that one would need to add some linear algebra functions of which the major would be Jordan decomposition and eigenvectors. Currently, we are trying to give GiNaC a try, but it is always good to keep in mind other alternatives, like Rings. Thanks for the link!

**Comment by magv** [comment]
Rings look considerably more advanced than GiNaC in polynomial algebra
respect, and Scala *is* an interesting language. Linear algebra would of
course need to be implemented on top, but that's not *that* big of a
problem. Thanks, Vladyslav, I haven't seen this library before.

As Oleksandr said, we're currently working on dropping Sage in favor of
plain GiNaC, so maybe if its limitations become unbearable, we'll need
to look at Rings more closely.

If Rings would support algebraic field extensions and linear algebra, we
would probably drop GiNaC in a heartbeat (if you know a library that
does all that, oh boy, would I be glad to see it).

**Comment by vsht** [comment]
Well, actually the author of Rings (PoslavskySV here on GitHub) has also developed a dedicated CAS called Redberry (http://redberry.cc). It has a strong focus on tensor algebra and QFT calculations, but I'm not sure if the linear algebra capabilities that you require are already implemented. I suppose that Rings is designed in such a way, that it can be easily used from Redberry.
